# -*- coding: utf-8 -*-
"""Threat-Intel Log Parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPQel5ykO7W8hiR8dmBYdWXb_pju7nhz
"""

import re
import requests
import time
import os
import sys

# --- CONFIGURATION ---
# Pro-tip: In a real job, use environment variables for keys!
API_KEY = "e367c0da4cba0dc4ef7f2e0f3da4f34e5afd98f43d06b0bd362be89a2f80b60d"
LOG_FILE = "/content/sample_data/access.log"  # Updated path to access.log
VT_URL = "https://www.virustotal.com/api/v3/ip_addresses/"

def extract_ips(file_path):
    """Extracts unique IPv4 addresses from a file with error handling."""
    if not os.path.exists(file_path):
        print(f"[-] Critical Error: File '{file_path}' not found.")
        return None

    try:
        with open(file_path, 'r') as f:
            log_data = f.read()
        # Improved Regex to ensure valid IP patterns
        ips = re.findall(r'\b(?:\d{1,3}\.){3}\d{1,3}\b', log_data)
        return set(ips)
    except Exception as e:
        print(f"[-] Error reading file: {e}")
        return None

def check_ip_reputation(ip):
    """Queries VirusTotal API and handles network/API errors."""
    headers = {"x-apikey": API_KEY}
    try:
        response = requests.get(VT_URL + ip, headers=headers, timeout=10)

        if response.status_code == 200:
            data = response.json()
            return data['data']['attributes']['last_analysis_stats'].get('malicious', 0)
        elif response.status_code == 401:
            print("[-] API Error: Invalid API Key.")
        elif response.status_code == 429:
            print("[-] API Error: Rate limit exceeded (Free tier: 4 req/min).")
        return 0
    except requests.exceptions.RequestException as e:
        print(f"[-] Network Error checking {ip}: {e}")
        return 0

def main():
    print("--- [ Automated Threat Intel Log Parser ] ---")

    # 1. Extract Data
    unique_ips = extract_ips(LOG_FILE)
    if unique_ips is None:
        sys.exit(1)

    if not unique_ips:
        print("[!] No IP addresses found in the log file.")
        return

    print(f"[*] Found {len(unique_ips)} unique IPs. Analyzing threats...")
    print("-" * 45)

    # 2. Process & Triage
    for ip in unique_ips:
        # Skip private/internal IPs to save API quota
        if ip.startswith(('127.', '192.168.', '10.')):
            print(f"[i] Skipping Internal IP: {ip}")
            continue

        malicious_count = check_ip_reputation(ip)

        if malicious_count > 0:
            print(f"[!] THREAT DETECTED: {ip} | Engines: {malicious_count}")
        else:
            print(f"[+] Clean: {ip}")

        # Free Tier Requirement: 15s delay between requests
        time.sleep(15)

    print("-" * 45)
    print("[*] Scan Complete.")

if __name__ == "__main__":
    main()

"""A score of 2 engines is a 'Low Confidence' alert. My next step would be to look at the specific vendors who flagged it. If they are reputable names like Palo Alto or Mandiant, I’d investigate further. If they are unknown vendors, it might be a false positive. I would also check the Community Comments on VirusTotal to see if other analysts have seen this IP linked to a recent campaign."""